# --- START OF FILE docker-compose.yml ---

version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      # Переменные окружения для настройки PostgreSQL - задаем значения напрямую
      # *** ИЗМЕНЕНИЕ ЗДЕСЬ ***
      POSTGRES_USER: test_user # Замените на ваше значение
      POSTGRES_PASSWORD: your_secure_password # Замените на ваше значение
      POSTGRES_DB: servicedesk_db # Замените на ваше значение
      # *** КОНЕЦ ИЗМЕНЕНИЯ ***
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d servicedesk_db"] # Обновите пользователя и БД здесь
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Сервис приложения FastAPI
  app:
    build:
      context: https://github.com/your_username/your_repository.git#your_branch_name # Замените на ваш username, repository и branch_name
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Переменные окружения для приложения - задаем значения напрямую
      # URL базы данных, используя имя сервиса БД 'db'
      DATABASE_URL: postgresql+asyncpg://test_user:your_secure_password@db:5432/servicedesk_db # Обновите пользователя, пароль и БД здесь
      # Переменные для ServiceDesk API
      BASE_URL: http://your-servicedesk-instance.com # Замените на ваш URL
      SDKEY: your_servicedesk_access_key
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs


volumes:
  db_data:
